#!/bin/bash
set -e

unset PREFIX npm_config_prefix
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

nvm use --delete-prefix

echo ">>>>> INSTALLING NPM DEPENDENCIES"
rm -rf node_modules
npm install
