#!/bin/bash
set -e

unset PREFIX npm_config_prefix
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

function updateRepo1 {
  if [ ! -d workspaces/$1 ]; then
    echo "Creating workspace $1"
    npm run add $1
  fi
  if [ ! -d workspaces/$1 ]; then
    echo "Workspace not found! $1" 1>&2
    exit 64
  fi
  echo Updating $1
  cd workspaces/$1
  sed -i -e 's/https...github.com./git@github.com:/g' .git/config
  git checkout main
  git reset origin/main
  git checkout -- .
  git pull
}
function updateRepo2 {
  nvm use --delete-prefix
  rm -rf node_modules
  rm package-lock.json
  npx npm-check-updates -u
  npm install
}
function updateRepo3 {
  npm test
  npm run build
  ( git commit -am"Update dependencies" && npm version patch && npm publish -timeout=9999999 ) || echo No change in $1
  git push origin main --follow-tags
  cd ../..
  echo Finished $1
}
function updateRepo {
  echo Starting $1
  updateRepo1 $1
  updateRepo2 $1
  updateRepo3 $1
}

updateRepo jose # @solid/jose
updateRepo oidc-rp # @solid/oidc-rp (@solid/jose)

updateRepo1 solid-auth-client # solid-auth-client (@babel/runtime, auth-header, commander, isomorphic-fetch, @solid/oidc-rp)
# updateRepo2 solid-auth-client
npm install @solid/oidc-rp@latest
updateRepo3 solid-auth-client

updateRepo1 rdflib # rdflib (jsonld, n3, xmldom)
updateRepo2 rdflib
npm install --save-dev webpack@4
npm install --save-dev source-map-loader@1
updateRepo3 rdflib

updateRepo pane-registry # pane-registry (rdflib)
updateRepo solid-namespace # solid-namespace
updateRepo solid-logic # solid-logic (rdflib, solid-namespace)
 
updateRepo1 solid-ui # solid-ui (pane-registry, solid-logic, rdflib, solid-auth-client, solid-namespace)
updateRepo2 solid-ui
npm install --save-dev webpack@4
npm install --save-dev webpack-cli@3
updateRepo3 solid-ui

updateRepo1 activitystreams-pane
updateRepo2 activitystreams-pane
npm install --save-dev webpack@4
npm install --save-dev webpack-cli@3
updateRepo3 activitystreams-pane

updateRepo1 chat-pane # chat-pane (solid-ui)
updateRepo2 chat-pane
npm install --save-dev webpack@4
npm install --save-dev webpack-cli@3
updateRepo3 chat-pane

updateRepo contacts-pane # contacts-pane (solid-ui)
updateRepo folder-pane # folder-pane (solid-ui)
updateRepo issue-pane # issue-pane (solid-ui, pane-registry, rdflib)

updateRepo1 meeting-pane # meeting-pane (solid-ui)
updateRepo2 meeting-pane
npm install --save-dev webpack@4
npm install --save-dev webpack-cli@3
updateRepo3 meeting-pane

updateRepo source-pane # source-pane (solid-ui)

updateRepo1 solid-panes # solid-panes (chat-pane, contacts-pane, folder-pane, issue-pane, meeting-pane, pane-registry, rdflib, solid-ui, source-pane)
updateRepo2 solid-panes
npm install --save-dev @typescript-eslint/eslint-plugin@3
npm install --save-dev @typescript-eslint/parser@3
npm install --save-dev webpack@4
npm install --save-dev webpack-cli@3
updateRepo3 solid-panes

updateRepo1 mashlib # mashlib (rdflib, solid-panes, solid-ui)
updateRepo2 mashlib
npm install --save-dev @typescript-eslint/eslint-plugin@3
npm install --save-dev @typescript-eslint/parser@3
npm install --save-dev webpack@4
npm install --save-dev webpack-cli@3
npm install --save-dev mini-css-extract-plugin@1.2
npm install --save-dev copy-webpack-plugin@6
npm install --save-dev html-webpack-plugin@4
updateRepo3 mashlib

updateRepo node-solid-ws # solid-ws ()
updateRepo node-webid # webid (rdflib)
updateRepo acl-check # @solid/acl-check (rdflib, solid-namespace)
updateRepo keychain # @solid/keychain
updateRepo oidc-op # @solid/oidc-op (@solid/keychain)
updateRepo oidc-rs # @solid/oidc-rs (@solid/jose)
updateRepo solid-multi-rp-client # @solid/solid-multi-rp-client (oidc-rp)
updateRepo oidc-auth-manager # @solid/oidc-auth-manager (oidc-rp, oidc-op, oidc-rs, solid-multi-rp-client)
updateRepo solid-auth-oidc # @solid/solid-auth-oidc (@solid/oidc-rp)

updateRepo1 node-solid-server # solid-server (@solid/acl-check, @solid/oidc-auth-manager, rdflib, mashlib, solid-auth-client, solid-namespace, solid-ws, @solid/oidc-op, @solid/solid-auth-oidc, webid)
updateRepo2 node-solid-server
npm install bootstrap@3
npm install --save-dev @solid/solid-auth-oidc@0.3.0
updateRepo3 node-solid-server

updateRepo1 solid-rest # solid-rest (concat-stream, cross-fetch, fs-extra, mime-types)
nvm use --delete-prefix
rm -rf node_modules
rm package-lock.json
npx npm-check-updates -u
npm install --save-dev webpack@4
updateRepo3 solid-rest

updateRepo solid-cli # solid-cli (@solid/oidc-rp)

# FIXME: https://github.com/solid/solid-auth-fetcher/issues/15
# updateRepo solid-auth-fetcher
updateRepo solid-node-client # solid-node-client (rdflib, solid-auth-fetcher, solid-rest)
updateRepo webid-provider-tests
updateRepo solid-crud-tests
updateRepo web-access-control-tests

# FIXME: https://github.com/solid/github-solid/pull/2
# updateRepo gitter-solid
# FIXME: https://github.com/solid/gitter-solid/pull/12
# updateRepo github-solid
