#!/bin/bash
set -e

echo ">>>>> SETTING UP/RESETTING PROJECT"
mkdir -p workspaces
rm -rf workspaces/*

declare -a packages=(
  "node-solid-server"
  "mashlib"
  "solid-panes"
  "solid-ui"
  "rdflib")

# Clone and npm install dependent packages
for package in "${packages[@]}"
do
  echo ""
  echo "# Installing $package"
  npm run add $package
done

# Disabled because lerna doesn't establish Node environment via nvm reliably
##
## npx lerna run build
##

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Build dependent packages, ensuring each is in proper Node environment via nvm
for package in "${packages[@]}"
do
  echo ""
  echo "# Building $package"
  pushd workspaces/$package
  nvm use --delete-prefix
  npm run build
  popd
done

openssl req -outform PEM -keyform PEM -new -x509 -sha256 -newkey rsa:2048 -nodes -keyout workspaces/privkey.pem -days 365 -out workspaces/fullchain.pem -subj "/C=RO/ST=Bucharest/L=Bucharest/O=IT/CN=localhost"
