#!/bin/bash

unset PREFIX npm_config_prefix
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

npx lerna bootstrap --force-local

cd workspaces/css-mashlib
nvm use --delete-prefix
npm run start:clean
